create table financa (id bigint generated by default as identity, total double not null, primary key (id));
create table transacoes (id bigint generated by default as identity, descricao varchar(255), valor_transacao double not null, financa_id bigint, primary key (id));
alter table transacoes add constraint FK2ax24id1c1sk29qve5385u5at foreign key (financa_id) references financa;

insert into financa (total) values (0.0)