create table entrada (id bigint generated by default as identity, descricao varchar(255), valor_entrada double not null, financa_id bigint, primary key (id));
create table financa (id bigint generated by default as identity, total double not null, primary key (id));
create table saida (id bigint generated by default as identity, descricao varchar(255), valor_saida double not null, financa_id bigint, primary key (id));
alter table entrada add constraint FK8el9aflgemt3xw2gtfmpmprm5 foreign key (financa_id) references financa;
alter table saida add constraint FKtpvv7c873v7qo3pbxo08733bl foreign key (financa_id) references financa;


insert into financa (total) values (0.0);